### PR TITLE
Changes in board layout to allow for mounting hole

### PR DESCRIPTION
**Pull request by amet**
Great work on this @zapta, I have installed it in my 991 and all is working great.

I have just made some changes in the board layout and having a sample PCB made, https://oshpark.com/projects/0eFiDi1B

I have also removed serial communication as the board can be programmed via Arduino IDE using USBASP programer, keeps the board same size and allows for the mounting hole to be drilled.

 - if we use 3 pin stackable header on the back of the board(slave connector) we can plug directly into the center console
 - added a hole in the boeard to screw into center console module, works on 991 not sure how much space there is in 981s

since I have not tested the boards, I cant comment on how/if it works but just throwing it out there if anyone wants to mess with it and I don't expect you to merge this :)

### CODE REVIEW

**Comment by zapta** [comment]
Hi Zeljko,

I am glad that it is useful for you. Your PCB looks very nice.

Can you make the changes in the shell script as comments?  I prefer not to
overwrite the existing setting (unless if there is a good reason for
changing the programmer type or the fuse setting).

Thanks,

Zapta.

**Comment by amet** [comment]
Hi Zapta,

not trying to reinvent the wheel here, just looking for a way to mount it on 991 :)

made changes as per your comment, should all be contained to 991 folder.

I am still waiting for the new boards, knowing me and my OCD there will be a version 2 and 3 still to come and since its all made in USA it might take a while to get it over to test. serial pins might still make it back into a bigger board design, not sure it was a wise idea to remove them.

thank for checking over it

amet

**Comment by zapta** [comment]
Hi Amet,

I just merged your pull request. Thanks.

As for the fuses, I am using the same fuse setting on all of my atmega328P
projects. Sometimes when it try to program via the ICSP it fails and then I
try again and it goes through. I also had to reduce the bit rate of the
programmer since it must be 1/4 of the MCU speed which is initially 1Mhz
with the RC oscilator (not 100% sure).

I mounted my board by first wrapping it with a wire clear shrink tube (as
done with some RC modules) and then used 3M industrial double tape to stick
it to a metal panel inside the center console of my Cayman 981 (I think
that from the seats, forward, it shares the same design as the (991).

Take care,

Zapta

**Comment by amet** [comment]
Hi,

Thanks for that... There is nothing wrong with current board layout, just for ease of mounting( and lack of better things to do) I decided to shuffle it around a bit to allow for the mounting hole.

Fuse is a funny one, I do all this on OS X and could not burn it with current setting... Read here (http://www.avrfreaks.net/forum/fuse-programming-error) that 0x05 and 0xfd is the same as it reads only bottom 3 bits

Will keep you posted on the new board layout, if all is good pics will follow.

Great job with the whole implementation , glad I found it :)

amet

**Comment by zapta** [comment]
Hi Amet,

I am also using OSX.  If you think that 0xfd is a good setting overall,
please send me a pull request and I will merge it.

Thanks,

Zapta

**Comment by amet** [comment]
Hi Zapta,

no need I think, its noted in the script... if anyone has issues they will figure it out :)

cheers,
amet

**Pull request merged**
